### ISSUE TITLE
Feature request: Detect images in the same directory as the current image by default

### ISSUE THREAD

**Issue by Zeioth** [artemsen/swayimg#26]
Currently, if I want to use pgDown/Up to view my images, I need to open swayimg like:

    swayimg image1 image2...
    swayimg script-that-passes-directory-images.sh

Which is ok. But since this is a common enough case of use, it would be important to have it detecting same directory images by default, to make it user friendly.

**Comment by artemsen** [comment]
Sorry, I didn't understand the idea =)
What does "detecting same directory images" mean? Could you give an example?

**Comment by Zeioth** [comment]
Current behavior:
* I open an image. I press the key 'page next'. It does nothing.

Expected behavior:
* I open an image. I press the key 'page next'. It displays the next image.

**Comment by artemsen** [comment]
There are so many "what if" =)
- What sort order should we apply to the list of files?
- Currently `swayimg` ignores the file extension. What if there are thousands of files on a network drive? We will try to open each file, even if it is not an image, this can be a very slow operation. Do we need to show some kind of a progress dialog?
- What about sub directories?
- Should we show the next image if there are two or more files specified on the command line, but the next file is not one of them?

Of course, we could add new command line arguments to control such behavior.
It will end up with own `find` tool =)
Sorry, I still believe in Unix philosophy: _Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features"._

**Comment by Zeioth** [comment]
This is literally the only image program I've ever used without such an elemental usability feature, but I guess anyone can fork it. Thanks.

**Comment by artemsen** [comment]
Ok, I give up =)
Let's do it in this way: if no input files were specified in command line, `swayimg` will iterate through all files in the current directory.
