### ISSUE TITLE
[Feature Request] Deletion of images

### ISSUE THREAD

**Issue by Pound-Hash** [artemsen/swayimg#28]
This could be my image viewer if it had the ability to delete images.

Thanks for the app

**Comment by artemsen** [comment]
View, mark, and remove all marked files in the current directory:
```
swayimg --mark | xargs -d '\n' rm
```

**Comment by Pound-Hash** [comment]
Thanks.

I used `swayimg --mark | parallel rm`

**Comment by Pound-Hash** [comment]
If I use the `--mark` option and mark all files with `a`, then swayimg will delete **all** the files, not just images.

Is this intended behavior?

**Comment by artemsen** [comment]
Yes, this is expected behavior.
When `swayimg` starts, it composes a file list to view.
In `-all` mode, or if there are directories in the input (as in your case: current dir by default), the list will contain all files, regardless of their type or extension. The files that cannot be loaded will be excluded from the list only when you try to open them with `n/N/p/P/PgUp/PgDown`.
You can use the globbing to add image only files, something like this: `swayimg --mark *.jpg`
