### ISSUE TITLE
[feature] Key binding to show key bindings

### ISSUE THREAD

**Issue by giraudan** [artemsen/swayimg#52]
Would it be possible to add a key binding that displays the key bindings, maybe identical to the way the image metadata is displayed when the `-i` command line argument is passed?

**Comment by artemsen** [comment]
Do you want something like help message (F1?) with key binding description?

**Comment by giraudan** [comment]
This is what I had in mind, yes.

**Comment by artemsen** [comment]
I'm not sure if this will help, but you can now create your [own keybindings](https://github.com/artemsen/swayimg/commit/e90e65cd1cb9d6cd7fa6cc42c91c178fe5c94bf7).

**Comment by Zeioth** [comment]
I think @giraudan mean something like ranger, where the keybindings are displayed on screen. This is a nice to have thing and if someone wants to submit a PR it would probably be cool, but I think there are other priorities at the moment, like 10 bits color support. 

An image viewer can be quite complex you want a full featured piece of software. Overall I'd rather let @artemsen do its own thing, for which I'm very grateful, and let external PRs address more complicated, or unimportant stuff.

**Comment by artemsen** [comment]
> I think @giraudan mean something like ranger, where the keybindings are displayed on screen.

Yes, I understand that. I mean, people need a help window if they can't remember all the keys. Even I don't remember them all =)
So instead of displaying a help window, you can now create your own key bindings.

> like 10 bits color support

Swayimg can decode such images, but they are always displayed in 8-bit mode.
Unfortunately, my monitor cannot display 10-bit color, so I have nothing to test HDR.
But you can open a new issue so I don't forget about this feature.
