### ISSUE TITLE
Recurse current directory?

### ISSUE THREAD

**Issue by githububub** [artemsen/swayimg#8]
Instead of having to glob the current directory in order to next/previous through images, perhaps being able to 'swayimg -r 004.jpg' and being able to view 003.jpg with PageUp/p and 005.jpg with PageDn/n...

**Comment by artemsen** [comment]
We have already discussed a similar question.
[I don't think it's a good idea.](https://github.com/artemsen/swayimg/pull/5#issuecomment-855347728)

**Comment by githububub** [comment]
Understood. While recursing a directory for supported images is straightforward enough with `fd .*\(jpe?g\|png\|webp\)$ -d1 -X swayimg` to index from the first image, `fd .*\(jpe?g\|png\|webp\)$ -d1 -X swayimg  002.jpg` "results in reindexing as follows:

003.jpg
002.jpg (being viewed)
001.jpg
002.jpg

Perhaps something along the lines of the -n switch of imv would allow us an easier way to script something to create an expected index.

**Comment by manio** [comment]
FWIW: I also miss this feature. I am starting `swayimg` with argument specifying an exact image path and it would be great if I could just read next/prev images from the same directory. Restarting `swayimg` with "." or _DIR_PATH_ as argument is inconvenient because I have to find the image I was viewing and it is more complicated when more files are in such a directory...

**Comment by smlx** [comment]
@manio this feature exists with the `--all` flag.

**Comment by manio** [comment]
Oh indeed, thanks! :)
