### ISSUE TITLE
Gif:  Animation.

### ISSUE THREAD

**Issue by duffydack** [artemsen/swayimg#9]
I'm guessing there is some roadblock already preventing this, as you support gif opening, but are there any plans to allow gif playing/looping?  imv is stealing my disk space still!

**Comment by artemsen** [comment]
The main roadblock is my laziness =)
I will think about animation.

**Comment by Seirdy** [comment]
Other animated formats include WebP and AVIF.

AVIF animation is actually pretty much AV1 video so it might be better to delegate that to a video player instead of swayimg (unfortunately FFmpeg doesn't support HEIF, which is the container for AVIF images). WebP animation however is quite different from VP8 video and might make sense for an image viewer.

**Comment by roland-rollo** [comment]
> The main roadblock is my laziness =) I will think about animation.

Is there any hope for animations (mainly for gif and jxl)?

**Comment by artemsen** [comment]
This feature is difficult to implement with the current architecture of `swayimg`.
And, to be honest, I personally will not use this functionality - I don't have gif files in my collection.
Sorry, there is almost no hope =)
